name: klaviyo_flutter_sdk_example
description: Example app for Klaviyo Flutter SDK
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  klaviyo_flutter_sdk:
    path: ../

  permission_handler: ^11.3.1
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true 