reviews:
  profile: assertive
  path_filters:
    - "!**/build/**"
    - "!**/.dart_tool/**"
    - "!**/*.g.dart"
    - "!**/*.freezed.dart"
    - "!**/*.mocks.dart"
    - "!**/pubspec.lock"
    - "!**/Pods/**"
  auto_review:
    drafts: false
    base_branches:
      - ".*"
  tools:
    swiftlint:
      enabled: true
      config_file: "ios/.swiftlint.yml"
